/* In the following "ACTION_FIXATE_SUGAR_PACKET" is really                    */
/* "ACTION_FIXATE_SUGAR", that sometimes directs fixation to the              */
/* sugar packet and sometimes to the sugar bowl. This is the ugly hack        */
/* employed by BP 2004.                                                       */

ActionType sequence_coffee1[37] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_TEAR_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee2[37] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PULL_OFF,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee3[37] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_TEAR_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee4[37] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PULL_OFF,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

/* coffee5 and coffee6 are variants of coffee that use an open sugar bowl */

ActionType sequence_coffee5[31] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee6[31] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee1_1sip[36] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_TEAR_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee2_1sip[36] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PULL_OFF,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee3_1sip[36] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_TEAR_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee4_1sip[36] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PULL_OFF,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

/* coffee5 and coffee6 are variants of coffee that use an open sugar bowl */

ActionType sequence_coffee5_1sip[30] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee6_1sip[30] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee1_error[33] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_TEAR_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_coffee2_error[33] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PULL_OFF,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_coffee3_error[33] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_TEAR_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_coffee4_error[33] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PULL_OFF,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_SAY_DONE};


ActionType sequence_coffee5_error[27] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_coffee6_error[27] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_coffee_s1_drink[26] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_TEAR_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee_s2_drink[26] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PULL_OFF,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee_c_drink[26] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee_drink[15] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee_start[11] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_tea1[20] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_TEAR_OPEN,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_STIR,

                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_SIP,
                    ACTION_SIP,
                    ACTION_SAY_DONE};

ActionType sequence_tea2[20] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_PUT_DOWN,
                    ACTION_PULL_OFF,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_SUGAR_BOWL,
                    ACTION_SCOOP,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_STIR,

                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_SIP,
                    ACTION_SIP,
                    ACTION_SAY_DONE};

/* tea3 is a variant of tea that uses an open sugar bowl */

ActionType sequence_tea3[18] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_SUGAR_BOWL,
                    ACTION_SCOOP,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_STIR,

                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_SIP,
                    ACTION_SIP,
                    ACTION_SAY_DONE};

ActionType sequence_tea1_1sip[19] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_TEAR_OPEN,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_STIR,

                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_SIP,
                    ACTION_SAY_DONE};

ActionType sequence_tea2_1sip[19] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_PUT_DOWN,
                    ACTION_PULL_OFF,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_SUGAR_BOWL,
                    ACTION_SCOOP,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_STIR,

                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_SIP,
                    ACTION_SAY_DONE};

/* tea3 is a variant of tea that uses an open sugar bowl */

ActionType sequence_tea3_1sip[17] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_SUGAR_BOWL,
                    ACTION_SCOOP,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_STIR,

                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_SIP,
                    ACTION_SAY_DONE};

ActionType sequence_tea_start[5] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_SAY_DONE};

ActionType sequence_tea1_error[16] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_TEAR_OPEN,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_STIR,

                    ACTION_SAY_DONE};

ActionType sequence_tea2_error[16] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_PUT_DOWN,
                    ACTION_PULL_OFF,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_SUGAR_BOWL,
                    ACTION_SCOOP,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_STIR,

                    ACTION_SAY_DONE};

ActionType sequence_tea1_with_cream[31] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_TEAR_OPEN,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_STIR,

                    ACTION_FIXATE_CARTON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_PEEL_OPEN,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_STIR,

                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_SIP,
                    ACTION_SIP,
                    ACTION_SAY_DONE};

ActionType sequence_tea2_with_cream[31] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_PUT_DOWN,
                    ACTION_PULL_OFF,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_SUGAR_BOWL,
                    ACTION_SCOOP,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_STIR,

                    ACTION_FIXATE_CARTON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_PEEL_OPEN,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_STIR,

                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_SIP,
                    ACTION_SIP,
                    ACTION_SAY_DONE};

ActionType sequence_sugar_pack[12] = {
                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_PICK_UP,
                    ACTION_TEAR_OPEN,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_STIR,

                    ACTION_PUT_DOWN,
                    ACTION_SAY_DONE};

ActionType sequence_sugar_bowl[12] = {
                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_PULL_OFF,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_SUGAR_BOWL,
                    ACTION_SCOOP,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_STIR,

                    ACTION_PUT_DOWN,
                    ACTION_SAY_DONE};

ActionType sequence_pickup_sip[3] = {
                    ACTION_PICK_UP,
                    ACTION_SIP,

                    ACTION_SAY_DONE};

