ActionType sequence_coffee1[37] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_TEAR_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee2[37] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_PUT_DOWN,
                        ACTION_PULL_OFF,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee3[37] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,
                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,
                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_TEAR_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee4[37] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_PUT_DOWN,
                        ACTION_PULL_OFF,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee1_error[33] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_TEAR_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_coffee2_error[33] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_PUT_DOWN,
                        ACTION_PULL_OFF,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_coffee3_error[33] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_TEAR_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_coffee4_error[33] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_PUT_DOWN,
                        ACTION_PULL_OFF,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_coffee_s1_error[22] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_PACKET,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_TEAR_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_coffee_s2_error[22] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_PUT_DOWN,
                        ACTION_PULL_OFF,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_SUGAR_BOWL,
                        ACTION_SCOOP,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_coffee_c_error[22] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_FIXATE_CARTON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_PEEL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_coffee_drink[15] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_SIP,
                        ACTION_SIP,
                        ACTION_SAY_DONE};

ActionType sequence_coffee_start[11] = {
                        ACTION_FIXATE_COFFEE_PACKET,
                        ACTION_PICK_UP,
                        ACTION_PULL_OPEN,
                        ACTION_FIXATE_CUP,
                        ACTION_POUR,
                        ACTION_FIXATE_SPOON,
                        ACTION_PUT_DOWN,
                        ACTION_PICK_UP,
                        ACTION_FIXATE_CUP,
                        ACTION_STIR,

                        ACTION_SAY_DONE};

ActionType sequence_tea1[20] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_TEAR_OPEN,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_STIR,

                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_SIP,
                    ACTION_SIP,
                    ACTION_SAY_DONE};

ActionType sequence_tea2[20] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_BOWL,
                    ACTION_PUT_DOWN,
                    ACTION_PULL_OFF,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_SUGAR_BOWL,
                    ACTION_SCOOP,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_STIR,

                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_SIP,
                    ACTION_SIP,
                    ACTION_SAY_DONE};

ActionType sequence_tea_start[5] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_SAY_DONE};

ActionType sequence_tea1_error[16] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_PACKET,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_TEAR_OPEN,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_STIR,

                    ACTION_SAY_DONE};

ActionType sequence_tea2_error[16] = {
                    ACTION_FIXATE_TEABAG,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_CUP,
                    ACTION_DIP,

                    ACTION_FIXATE_SUGAR_BOWL,
                    ACTION_PUT_DOWN,
                    ACTION_PULL_OFF,
                    ACTION_FIXATE_SPOON,
                    ACTION_PUT_DOWN,
                    ACTION_PICK_UP,
                    ACTION_FIXATE_SUGAR_BOWL,
                    ACTION_SCOOP,
                    ACTION_FIXATE_CUP,
                    ACTION_POUR,
                    ACTION_STIR,

                    ACTION_SAY_DONE};

ActionType sequence_pickup_sip[3] = {
                    ACTION_PICK_UP,
                    ACTION_SIP,

                    ACTION_SAY_DONE};

